[build]
  command = "npm run build"
  functions = "api"
  publish = ".next"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[env]
  [env.production]
    environment = { NODE_VERSION = "20" }
